Added a couple of GCP, kubecluster scripts in .zshrc

diff --git a/packages/zsh/zshrc b/packages/zsh/zshrc
--- a/packages/zsh/zshrc
+++ b/packages/zsh/zshrc
@@ -2,7 +2,7 @@
 export PATH="$HOME/bin:/usr/local/bin:$PATH"
 
 # Path to your oh-my-zsh installation.
-  export ZSH="/home/ray/.oh-my-zsh"
+export ZSH="/home/raytung/.oh-my-zsh"
 
 # Set name of the theme to load --- if set to "random", it will
 # load a random theme each time oh-my-zsh is loaded, in which case,
@@ -96,10 +96,61 @@ export SSH_KEY_PATH="~/.ssh/id_rsa"
 # alias ohmyzsh="mate ~/.oh-my-zsh"
 # export PATH="$HOME/.cargo/bin:$PATH"
 
-export GOPATH="${HOME}/Code/gopath"
-export PATH="${PATH}:${HOME}/Code/flutter/bin"
-export PATH="${PATH}:${HOME}/Code/dotfiles/bin"
+export GOPATH="${HOME}"
+export PATH="${PATH}:${HOME}/src/github.com/raytung/dotfiles/bin"
 export PATH="${PATH}:${GOPATH}/bin"
 
 export VISUAL=vim
 export EDITOR="$VISUAL"
+
+if ps -p "${SSH_AGENT_PID}" > /dev/null; then
+  echo "SSH agent is already running"
+else
+  eval "$(ssh-agent)"
+fi
+
+kubecluster() {
+  echo "Current context is $(kubectl config current-context)"
+  echo -e "\nSelect context to change to:\n"
+  select context in $(kubectl config get-contexts --no-headers=true -o name); do
+    echo
+    echo "Setting context to ${context}"
+    kubectl config use-context "${context}"
+    break
+  done
+}
+
+gproj() {
+  echo "Current project is $(gcloud config list --format "get(core.project)")"
+  echo -e "\nSelect project:\n"
+  select project in $(gcloud projects list --format "get(project_id)"); do
+    echo
+    echo "Setting project to ${project}"
+    gcloud config set project "${project}"
+    break
+  done
+}
+
+reload() {
+  source ~/.zshrc
+}
+
+aws-creds() {
+  local profile="$1"
+  local id="$(aws configure get aws_access_key_id --profile "${profile}")"
+  if [ "${id}" = "" ]; then
+    echo "Unable to get aws access key id"
+    exit 1
+  fi
+
+  local key="$(aws configure get aws_secret_access_key --profile "${profile}")"
+  if [ "${key}" = "" ]; then
+    echo "Unable to get aws secret access key"
+    exit 1
+  fi
+
+  export AWS_ACCESS_KEY_ID="${id}"
+  export AWS_SECRET_ACCESS_KEY="${key}"
+}
+
+source ~/.zshrc.private
